[package]
name = "karlsen-miner"
version = "0.1.0"
edition = "2021"

readme = "README.md"
description = "A simple miner for Karlsen"

[lib]
crate-type = ["staticlib"]
name = "kls"

[dependencies]
blake3 = "1.5.0"
keccak = { version = "0.1" }
sha3 ={ version = "0.10.8"}
libc="*"
